package Total_Drama

type Person struct {
	Name           string `json:"name"`
	F_team         string `json:"f_team"`
	Gender         string `json:"gender"`
	Number_seasons int    `json:"number_seasons"`
	Position       string `json:"position"`
	Hair           string `json:"hair"`
	Power_10       int    `json:"power_10"`
}

var Characters = []Person{
	{
		Name:           "Dawn",
		F_team:         "Toxic Rats",
		Gender:         "Female",
		Number_seasons: 1,
		Position:       "Good",
		Hair:           "Blonde",
		Power_10:       8,
	},
	{
		Name:           "Lightning",
		F_team:         "Toxic Rats",
		Gender:         "Male",
		Number_seasons: 2,
		Position:       "Neutral",
		Hair:           "Black",
		Power_10:       9,
	},
	{
		Name:           "B",
		F_team:         "Toxic Rats",
		Gender:         "Male",
		Number_seasons: 1,
		Position:       "Good",
		Hair:           "Black",
		Power_10:       10,
	},
	{
		Name:           "Scott",
		F_team:         "Toxic Rats",
		Gender:         "Male",
		Number_seasons: 2,
		Position:       "Evil",
		Hair:           "Ginger",
		Power_10:       8,
	},
	{
		Name:           "Jo",
		F_team:         "Mutant Maggots",
		Gender:         "Female",
		Number_seasons: 2,
		Position:       "Evil",
		Hair:           "Blonde",
		Power_10:       10,
	},
	{
		Name:           "Brick",
		F_team:         "Mutant Maggots",
		Gender:         "Male",
		Number_seasons: 1,
		Position:       "Good",
		Hair:           "Black",
		Power_10:       7,
	},
	{
		Name:           "Cameron",
		F_team:         "Mutant Maggots",
		Gender:         "Male",
		Number_seasons: 2,
		Position:       "Good",
		Hair:           "Black",
		Power_10:       3,
	},
	{
		Name:           "Heather",
		F_team:         "Team Amazon",
		Gender:         "Female",
		Number_seasons: 4,
		Position:       "Evil",
		Hair:           "Black",
		Power_10:       6,
	},
	{
		Name:           "Gwen",
		F_team:         "Team Amazon",
		Gender:         "Female",
		Number_seasons: 4,
		Position:       "Good",
		Hair:           "Blue",
		Power_10:       6,
	},
	{
		Name:           "Alejandro",
		F_team:         "Team Chris Is Really Really Really Really Hot",
		Gender:         "Male",
		Number_seasons: 2,
		Position:       "Evil",
		Hair:           "Black",
		Power_10:       10,
	},
	{
		Name:           "Noah",
		F_team:         "Team Chris Is Really Really Really Really Hot",
		Gender:         "Male",
		Number_seasons: 4,
		Position:       "Neutral",
		Hair:           "Black",
		Power_10:       4,
	},
	{
		Name:           "Sierra",
		F_team:         "Team Chris Is Really Really Really Really Hot",
		Gender:         "Female",
		Number_seasons: 2,
		Position:       "Good",
		Hair:           "Purple",
		Power_10:       9,
	},
	{
		Name:           "Duncan",
		F_team:         "Killer Bass",
		Gender:         "Male",
		Number_seasons: 4,
		Position:       "Neutral",
		Hair:           "Green",
		Power_10:       10,
	},
	{
		Name:           "Dj",
		F_team:         "Killer Bass",
		Gender:         "Male",
		Number_seasons: 3,
		Position:       "Good",
		Hair:           "Black",
		Power_10:       6,
	},
	{
		Name:           "Geoff",
		F_team:         "Killer Bass",
		Gender:         "Male",
		Number_seasons: 4,
		Position:       "Good",
		Hair:           "Blonde",
		Power_10:       7,
	},
	{
		Name:           "Harold",
		F_team:         "Killer Bass",
		Gender:         "Male",
		Number_seasons: 3,
		Position:       "Neutral",
		Hair:           "Ginger",
		Power_10:       4,
	},
	{
		Name:           "Bridgette",
		F_team:         "Killer Bass",
		Gender:         "Female",
		Number_seasons: 3,
		Position:       "Good",
		Hair:           "Blonde",
		Power_10:       6,
	},
	{
		Name:           "Courtney",
		F_team:         "Killer Bass",
		Gender:         "Female",
		Number_seasons: 4,
		Position:       "Evil",
		Hair:           "Black",
		Power_10:       8,
	},
	{
		Name:           "Leshawna",
		F_team:         "Screaming Gophers",
		Gender:         "Female",
		Number_seasons: 3,
		Position:       "Neutral",
		Hair:           "Black",
		Power_10:       8,
	},
	{
		Name:           "Lindsay",
		F_team:         "Screaming Gophers",
		Gender:         "Female",
		Number_seasons: 4,
		Position:       "Good",
		Hair:           "Blonde",
		Power_10:       1,
	},
	{
		Name:           "Beth",
		F_team:         "Screaming Gophers",
		Gender:         "Female",
		Number_seasons: 3,
		Position:       "Good",
		Hair:           "Black",
		Power_10:       2,
	},
	{
		Name:           "Trent",
		F_team:         "Screaming Gophers",
		Gender:         "Male",
		Number_seasons: 3,
		Position:       "Good",
		Hair:           "Black",
		Power_10:       7,
	},
	{
		Name:           "Owen",
		F_team:         "Screaming Gophers",
		Gender:         "Male",
		Number_seasons: 4,
		Position:       "Good",
		Hair:           "Blonde",
		Power_10:       7,
	},
	{
		Name:           "Cody",
		F_team:         "Screaming Gophers",
		Gender:         "Male",
		Number_seasons: 3,
		Position:       "Good",
		Hair:           "Black",
		Power_10:       2,
	},
}
